### ISSUE TITLE
Issue while building from source

### ISSUE THREAD

**Issue by mqese** [emulatorjs/emulatorjs#395]
Hey Ethana et al.,

Recently I've tried hosting EmulatorJS on my own site (an Angular project), I was able to get it to work locally (via loading two separate JS files, the script containing EJS settings, and the actual loader.js), as well as publicly on my site. This was using /data/ cloned from this repository. After some modifications to file paths, the emulator worked great both locally and on production. After a day or two, the emulator stopped loading on production (not much debugging here, ```EJS_DEBUG_XX``` seems to have no effect, and the minified.js version is loaded regardless.). Before I go into more detail here, this issue requires its own ticket, but just wanted to set some context on how I got to this point. The TLDR is: using .js data cloned from here, had it working on production and local, stopped working on production, figured I'd try building from source. 

I decided it may be beneficial to build from source myself, using given instructions [here](https://emulatorjs.netlify.app/docs/Building.html). I've cloned the repositories, built the .bc file (```fceumm_libretro_emscripten.bc```), and placed it in the ```/dist-scripts/``` folder in RetroArch's directory (**NOTE:**, the instructions state to place this .bc file in ```/dist-cores/```, but I can not find such a directory on my box.). I installed all required packages as per the command in the beginning of the instructions.

I also wanted to make a note of the excellent work that everyone has done with this project. As I said previously, I had it working locally, and it's wonderfully executed, seriously well done, and I don't think you get enough praise.

The script quickly fails on build, stack trace below. I will post my environment details as well, below:

**System Details:**
OS: Ubuntu 22.04.1 LTS x86_64
Kernel: 5.15.0-1017-aws

As you may be able to tell, this is Ubuntu 22.04.1 hosted on an AWS EC2 instance, unsure if this is a factor.

**Stacktrace:**
```make: ./dist-cores.sh emscripten
make: Entering directory '/home/ubuntu/libretro-fceumm/RetroArch'
rm -rf obj-emscripten
rm -f retroarch.js
make: Leaving directory '/home/ubuntu/libretro-fceumm/RetroArch'
Buildbot: building for emscripten
-- Building core: fceumm --
NAME: fceumm
ASYNC: 0
PTHREAD: 0
LTO: 0
WASM: 1
GLES3: 0
STACK_MEMORY: 8388608
HEAP_MEMORY: 268435456
BUILD COMMAND: make -C ../ -f Makefile.emscripten  PTHREAD=0 ASYNC=0 WASM=1  LTO=0 HAVE_OPENGLES3=0 STACK_MEMORY=8388608 HEAP_MEMORY=268435456                                      -j7 TARGET=fceumm_libretro.js
make: Entering directory '/home/ubuntu/libretro-fceumm/RetroArch'
CC version_git.c
CC frontend/frontend_driver.c
CC retroarch.c
CC runloop.c
CC driver.c
CC ui/ui_companion_driver.c
CC camera/camera_driver.c
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc.py", line 3929, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/emcc.py", line 3922, in main
    ret = run(args)
  File "/usr/share/emscripten/emcc.py", line 1146, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/emcc.py", line 2651, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/usr/share/emscripten/emcc.py", line 2631, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/usr/share/emscripten/emcc.py", line 2572, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args) + compile_args + [src_file]
  File "/usr/share/emscripten/emcc.py", line 899, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 364, in add_cflags
    port.get(Ports, settings, shared)
  File "/usr/share/emscripten/tools/ports/zlib.py", line 19, in get
    ports.fetch_project('zlib', f'https://storage.googleapis.com/webassembly/emscripten-ports/zlib-{VERSION}.zip', 'zlib-' + VERSION, sha512has                                     h=HASH)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 247, in fetch_project
    with shared.Cache.lock():
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/share/emscripten/tools/cache.py", line 74, in lock
    self.acquire_cache_lock()
  File "/usr/share/emscripten/tools/cache.py", line 43, in acquire_cache_lock
    raise Exception('Attempt to lock the cache but FROZEN_CACHE is set')
Exception: Attempt to lock the cache but FROZEN_CACHE is set
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc.py", line 3929, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/emcc.py", line 3922, in main
    ret = run(args)
  File "/usr/share/emscripten/emcc.py", line 1146, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/emcc.py", line 2651, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/usr/share/emscripten/emcc.py", line 2631, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/usr/share/emscripten/emcc.py", line 2572, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args) + compile_args + [src_file]
  File "/usr/share/emscripten/emcc.py", line 899, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 364, in add_cflags
    port.get(Ports, settings, shared)
  File "/usr/share/emscripten/tools/ports/zlib.py", line 19, in get
    ports.fetch_project('zlib', f'https://storage.googleapis.com/webassembly/emscripten-ports/zlib-{VERSION}.zip', 'zlib-' + VERSION, sha512has                                     h=HASH)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 247, in fetch_project
    with shared.Cache.lock():
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/share/emscripten/tools/cache.py", line 74, in lock
    self.acquire_cache_lock()
  File "/usr/share/emscripten/tools/cache.py", line 43, in acquire_cache_lock
    raise Exception('Attempt to lock the cache but FROZEN_CACHE is set')
Exception: Attempt to lock the cache but FROZEN_CACHE is set
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc.py", line 3929, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/emcc.py", line 3922, in main
    ret = run(args)
  File "/usr/share/emscripten/emcc.py", line 1146, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/emcc.py", line 2651, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/usr/share/emscripten/emcc.py", line 2631, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/usr/share/emscripten/emcc.py", line 2572, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args) + compile_args + [src_file]
  File "/usr/share/emscripten/emcc.py", line 899, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 364, in add_cflags
    port.get(Ports, settings, shared)
  File "/usr/share/emscripten/tools/ports/zlib.py", line 19, in get
    ports.fetch_project('zlib', f'https://storage.googleapis.com/webassembly/emscripten-ports/zlib-{VERSION}.zip', 'zlib-' + VERSION, sha512has                                     h=HASH)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 247, in fetch_project
    with shared.Cache.lock():
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/share/emscripten/tools/cache.py", line 74, in lock
    self.acquire_cache_lock()
  File "/usr/share/emscripten/tools/cache.py", line 43, in acquire_cache_lock
    raise Exception('Attempt to lock the cache but FROZEN_CACHE is set')
Exception: Attempt to lock the cache but FROZEN_CACHE is set
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc.py", line 3929, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/emcc.py", line 3922, in main
    ret = run(args)
  File "/usr/share/emscripten/emcc.py", line 1146, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/emcc.py", line 2651, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/usr/share/emscripten/emcc.py", line 2631, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/usr/share/emscripten/emcc.py", line 2572, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args) + compile_args + [src_file]
  File "/usr/share/emscripten/emcc.py", line 899, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 364, in add_cflags
    port.get(Ports, settings, shared)
  File "/usr/share/emscripten/tools/ports/zlib.py", line 19, in get
    ports.fetch_project('zlib', f'https://storage.googleapis.com/webassembly/emscripten-ports/zlib-{VERSION}.zip', 'zlib-' + VERSION, sha512has                                     h=HASH)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 247, in fetch_project
    with shared.Cache.lock():
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/share/emscripten/tools/cache.py", line 74, in lock
    self.acquire_cache_lock()
  File "/usr/share/emscripten/tools/cache.py", line 43, in acquire_cache_lock
    raise Exception('Attempt to lock the cache but FROZEN_CACHE is set')
Exception: Attempt to lock the cache but FROZEN_CACHE is set
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc.py", line 3929, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/emcc.py", line 3922, in main
    ret = run(args)
  File "/usr/share/emscripten/emcc.py", line 1146, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/emcc.py", line 2651, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/usr/share/emscripten/emcc.py", line 2631, in compile_source_file
Traceback (most recent call last):
  File "/usr/share/emscripten/emcc.py", line 3929, in <module>
    sys.exit(main(sys.argv))
    cmd = get_clang_command(input_file)
  File "/usr/share/emscripten/emcc.py", line 2572, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args) + compile_args + [src_file]
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/emcc.py", line 3922, in main
    ret = run(args)
  File "/usr/share/emscripten/emcc.py", line 899, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 364, in add_cflags
    port.get(Ports, settings, shared)
  File "/usr/share/emscripten/tools/ports/zlib.py", line 19, in get
  File "/usr/share/emscripten/emcc.py", line 1146, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
    ports.fetch_project('zlib', f'https://storage.googleapis.com/webassembly/emscripten-ports/zlib-{VERSION}.zip', 'zlib-' + VERSION, sha512has                                     h=HASH)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 247, in fetch_project
    with shared.Cache.lock():
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/tools/cache.py", line 74, in lock
    self.acquire_cache_lock()
  File "/usr/share/emscripten/emcc.py", line 2651, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/usr/share/emscripten/tools/cache.py", line 43, in acquire_cache_lock
    raise Exception('Attempt to lock the cache but FROZEN_CACHE is set')
Exception: Attempt to lock the cache but FROZEN_CACHE is set
  File "/usr/share/emscripten/emcc.py", line 2631, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/usr/share/emscripten/emcc.py", line 2572, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args) + compile_args + [src_file]
  File "/usr/share/emscripten/emcc.py", line 899, in get_cflags
Traceback (most recent call last):
make: *** [Makefile.emscripten:195: obj-emscripten/version_git.o] Error 1
make: *** Waiting for unfinished jobs....
  File "/usr/share/emscripten/emcc.py", line 3929, in <module>
    sys.exit(main(sys.argv))
    ports.add_cflags(cflags, settings)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 364, in add_cflags
    port.get(Ports, settings, shared)
  File "/usr/share/emscripten/tools/ports/zlib.py", line 19, in get
    ports.fetch_project('zlib', f'https://storage.googleapis.com/webassembly/emscripten-ports/zlib-{VERSION}.zip', 'zlib-' + VERSION, sha512has                                     h=HASH)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 247, in fetch_project
    with shared.Cache.lock():
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/share/emscripten/emcc.py", line 3922, in main
    ret = run(args)
  File "/usr/share/emscripten/tools/cache.py", line 74, in lock
    self.acquire_cache_lock()
  File "/usr/share/emscripten/tools/cache.py", line 43, in acquire_cache_lock
    raise Exception('Attempt to lock the cache but FROZEN_CACHE is set')
Exception: Attempt to lock the cache but FROZEN_CACHE is set
  File "/usr/share/emscripten/emcc.py", line 1146, in run
    linker_inputs = phase_compile_inputs(options, state, newargs, input_files)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/share/emscripten/emcc.py", line 2651, in phase_compile_inputs
    compile_source_file(i, input_file)
  File "/usr/share/emscripten/emcc.py", line 2631, in compile_source_file
    cmd = get_clang_command(input_file)
  File "/usr/share/emscripten/emcc.py", line 2572, in get_clang_command
    return get_compiler(src_file) + get_cflags(state.orig_args) + compile_args + [src_file]
  File "/usr/share/emscripten/emcc.py", line 899, in get_cflags
    ports.add_cflags(cflags, settings)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 364, in add_cflags
    port.get(Ports, settings, shared)
  File "/usr/share/emscripten/tools/ports/zlib.py", line 19, in get
    ports.fetch_project('zlib', f'https://storage.googleapis.com/webassembly/emscripten-ports/zlib-{VERSION}.zip', 'zlib-' + VERSION, sha512has                                     h=HASH)
  File "/usr/share/emscripten/tools/ports/__init__.py", line 247, in fetch_project
    with shared.Cache.lock():
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/share/emscripten/tools/cache.py", line 74, in lock
    self.acquire_cache_lock()
  File "/usr/share/emscripten/tools/cache.py", line 43, in acquire_cache_lock
    raise Exception('Attempt to lock the cache but FROZEN_CACHE is set')
Exception: Attempt to lock the cache but FROZEN_CACHE is set
make: *** [Makefile.emscripten:195: obj-emscripten/frontend/frontend_driver.o] Error 1
make: *** [Makefile.emscripten:195: obj-emscripten/retroarch.o] Error 1
make: *** [Makefile.emscripten:195: obj-emscripten/runloop.o] Error 1
make: *** [Makefile.emscripten:195: obj-emscripten/driver.o] Error 1
make: *** [Makefile.emscripten:195: obj-emscripten/ui/ui_companion_driver.o] Error 1
make: *** [Makefile.emscripten:195: obj-emscripten/camera/camera_driver.o] Error 1
make: Leaving directory '/home/ubuntu/libretro-fceumm/RetroArch'
emmake: error: './dist-cores.sh emscripten' failed (returned 1)
```

**Comment by ethanaobrien** [comment]
The building from source is actually for the cores themselves, not the JavaScript side which seems to be the problem (although, when building from source I've never seen that error). Could you send me your html code, a log of the console with `EJS_DEBUG_XX` set to true, and a screenshot of the network log? I'm pretty sure I know what the problem is, but I need this information to verify it

**Comment by mqese** [comment]
Hey, thanks for the quick reply,

I'm sure the cores cloned are perfectly fine, so building from source will no longer be relevant (which means this issue/ticket is going a bit off-topic now, sorry about that.)

I opted to "start from scratch", re-cloned the ```/data/``` directory and start anew. I'll paste all relevant snippets below 

**HTML**
The HTML on its own only serves to create a div and give it the necessary ID so emulatorJS can find it.
```

<div style='width:640px;height:480px;max-width:100%;margin: 0 auto;'>
    <p style="text-align: center;">* This only works on desktop, it'll never work on mobile. *</p>
    <div id='game'></div>
</div>

<br>
<br>
<p style="text-align: center;">* If the emulator freezes on initial load, refresh the page! *</p>

<app-base-footer></app-base-footer>
```

The js itself is actually loaded by binding/targeting the HTML in Typescript, if that makes sense.

**TypeScript**
```
export class ArcadeComponent implements OnInit {

  constructor(
    private renderer: Renderer2,
    route: ActivatedRoute , public router: Router , 
    @Inject(DOCUMENT) private _document: Document
  ) { }

  ngOnInit(): void {
     this.loadNextScript();
  }

  ngAfterViewInit(){
    this.loadEmu();
  }

  loadEmu() {
    var s = this.renderer.createElement("script");
     s.onload = this.loadNextScript.bind(this);
    s.type = "text/javascript";
    s.src = "assets/data/loader.js";

    this.renderer.appendChild(this._document.body, s);
  }

  loadGameboy() {
    const s = this.renderer.createElement('script');
    s.text =
   `EJS_player = "#game";
    EJS_core = "gb";
    EJS_gameName = "Pokemon Gold";
    EJS_color = "#9b13ec";
    EJS_pathtodata = "";
    EJS_DEBUG_XX = true;
    EJS_startOnLoaded = false;
    EJS_gameUrl = "assets/pkmngold.gbc";`
    this.renderer.appendChild(this._document.body, s);
  }
  
  loadNextScript() {
    const s = this.renderer.createElement('script');
    s.text =
   `EJS_DEBUG_XX = true;
    EJS_player = "#game";
    EJS_core = "snes";
    EJS_gameName = "Super Mario World";
    EJS_color = "#9b13ec";
    EJS_pathtodata = "assets/data/";
    EJS_startOnLoaded = false;
    EJS_gameUrl = "assets/smw.sfc";`
    this.renderer.appendChild(this._document.body, s);
 }
}
```

A bit of explanation, since none of this is commented out. Basically the ```EJS_*``` settings are loaded dynamically as a script, most importantly **before** loader.js is loaded, this was normally done via the .bind() function (note that loader.js isn't called until ngAfterViewInit, giving the "EJS_*" script time to load, For this ticket, I've opted to just load the EJS_* settings in ngOnInit()

At the time of writing this, the emulator is actually working fine on production (not sure if posting link is allowed/necessary, I'll include if needed). The main difference I made is loading the EJS settings in ngOnInit(). With debug enabled (which is now being seen correctly), I do see an uncaught property error (Right after ```[INFO] [Environ]: SET_GEOMETRY.```), but the game/emulator itself is loading fine. I'll put relevant details below.

```
N https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    (Async: promise callback)
    q https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    N https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    B https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    _0xbae705 https://marke.se/world/assets/data/emu-main.js?v=30.5:255
    start https://marke.se/world/assets/data/emu-main.js?v=30.5:1530
    _0x3512e9 https://marke.se/world/assets/data/emu-main.js?v=30.5:1598
    _0x5048db https://marke.se/world/assets/data/emu-main.js?v=30.5:1681
    oncomplete https://marke.se/world/assets/data/emulator.js?v=30.5:510
    We https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    invokeTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    runTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    invokeTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    Z https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    N https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    B https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    (Async: EventListener.handleEvent)
    t https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    scheduleTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    scheduleTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    scheduleEventTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    u https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    set https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    get https://marke.se/world/assets/data/emulator.js?v=30.5:509
    _0x5048db https://marke.se/world/assets/data/emu-main.js?v=30.5:1679
    invoke https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    run https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    ee https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    invokeTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    runTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    _ https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    (Async: promise callback)
    q https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    R https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    scheduleTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    scheduleTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    scheduleMicroTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    ee https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    z https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    I https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    w https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    (Async: promise callback)
    then https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    t https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    then https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    _0x5048db https://marke.se/world/assets/data/emu-main.js?v=30.5:1631
    _0x139f68 https://marke.se/world/assets/data/emu-main.js?v=30.5:1748
    _0x452592 https://marke.se/world/assets/data/emu-main.js?v=30.5:1808
    _0x10b71a https://marke.se/world/assets/data/emu-main.js?v=30.5:1960
    monitorRunDependencies https://marke.se/world/assets/data/emu-main.js?v=30.5:1971
    removeRunDependency https://marke.se/world/assets/data/emu-main.js?v=30.5 line 2000 > eval:1
    receiveInstance https://marke.se/world/assets/data/emu-main.js?v=30.5 line 2000 > eval:1
    receiveInstantiationResult https://marke.se/world/assets/data/emu-main.js?v=30.5 line 2000 > eval:1
    invoke https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    run https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    ee https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    invokeTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    runTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    _ https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    (Async: promise callback)
    q https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    R https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    scheduleTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    scheduleTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    scheduleMicroTask https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    ee https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    z https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    I https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    w https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    (Async: promise callback)
    then https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    t https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    then https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
    z https://marke.se/world/polyfills.d81b26c09f5f1eee.js:1
```

I realize now, with this error, I've gone completely off-topic of the original Issue, so if you'd like to close (I can always remake another Issue if needed regarding the error immediately above), that is fine by me.

**Comment by ethanaobrien** [comment]
Being off topic is fine, you can always rename the issue if you'd like

From the looks of the code, from my point of view it looks like the loader.js file is loaded before all the configuration variables. Could you make sure this isn't happening?

**Comment by ethanaobrien** [comment]
Closing from inactivity, if you're still having problems please leave a comment and I can try to help
