### ISSUE TITLE
[Bug] PSP - Failed to start game (cannot call unknown function set_ff_ratio)

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#646]
Hi,

I've tried to run random psp roms, and everytime i get the same error message after the game is loaded:

Aborted(Assertion failed: Cannot call unknown function set_ff_ratio, make sure it is exported)
emulator.js:1044 failed to start game RuntimeError: Aborted(Assertion failed: Cannot call unknown function set_ff_ratio, make sure it is exported)
    at abort (9e1e3afe-5ef9-49ca-8148-e470a9afa7b7:636:10)
    at assert (9e1e3afe-5ef9-49ca-8148-e470a9afa7b7:354:3)
    at getCFunc (9e1e3afe-5ef9-49ca-8148-e470a9afa7b7:13398:2)
    at ccall (9e1e3afe-5ef9-49ca-8148-e470a9afa7b7:13424:13)
    at Object.setFastForwardRatio (9e1e3afe-5ef9-49ca-8148-e470a9afa7b7:13461:10)
    at EJS_GameManager.setFastForwardRatio (GameManager.js:316:24)
    at EmulatorJS.menuOptionChanged (emulator.js:3271:34)
    at addToMenu (emulator.js:3437:26)
    at EmulatorJS.setupSettingsMenu (emulator.js:3481:9)
    at EmulatorJS.startGame (emulator.js:1019:18)

**Comment by ethanaobrien** [comment]
>PSP is not yet supported. Some of y'all may have seen that I pushed a "beta" ppsspp core, but this core is not ready for daily use. It still crashes randomly and any games that use 3d (so like, all of them) will just have a white screen (and might just crash). **Do not open issues related to the "psp" core.**

**Comment by shaylevary** [comment]
Ok, Sorry.
I thought i can start testing it, as appeared on your discussion about the beta psp:
"**_if you add the psp core to your site, it is recommended to fully test the game first ... It seems my initial conclusion of 3d was incorrect. Some 3d games seem to work_**"
https://github.com/orgs/EmulatorJS/discussions/569

Anyway, i'll wait with testing this "psp" core until it will be ready for tests.

**Comment by ethanaobrien** [comment]
Let's say that at the moment, it doesn't look like psp is happening
